// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ibDiary_data.Data;

#nullable disable

namespace ibDiary_data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827141959_V1AddValidation")]
    partial class V1AddValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ibDiary_data.Models.Calendar.CalendarDay", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("CalendarDays");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.HasIndex("MealId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.FoodItemReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AteFoodAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.HasIndex("FoodItemId");

                    b.ToTable("FoodReports");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.MealReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AteMealAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.HasIndex("MealId");

                    b.ToTable("MealReports");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrescribedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrescribedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.HasIndex("MedicineScheduleId")
                        .IsUnique();

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.MedicineReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MedicineTaken")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MedicineTakenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.HasIndex("MedicineId");

                    b.ToTable("MedicineReports");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.MedicineSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MedicineSchedules");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.MedicineStateChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicineAfter")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MedicineBefore")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MedicineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.HasIndex("MedicineId");

                    b.ToTable("MedicineStateChanges");
                });

            modelBuilder.Entity("ibDiary_data.Models.Settings.ScheduledNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.ToTable("ScheduledNotifications");
                });

            modelBuilder.Entity("ibDiary_data.Models.Symptoms.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("ibDiary_data.Models.Symptoms.SymptomReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedFor")
                        .HasColumnType("TEXT");

                    b.Property<int>("SymptomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.HasIndex("MedicationId");

                    b.HasIndex("SymptomId");

                    b.ToTable("SymptomReports");
                });

            modelBuilder.Entity("ibDiary_data.Models.Symptoms.SymptomStateChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CalendarDayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymptomAfter")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SymptomBefore")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SymptomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDayDate");

                    b.HasIndex("SymptomId");

                    b.ToTable("SymptomStateChanges");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.FoodItem", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("CreatedFoods")
                        .HasForeignKey("CalendarDayDate");

                    b.HasOne("ibDiary_data.Models.Food.Meal", null)
                        .WithMany("FoodItems")
                        .HasForeignKey("MealId");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.FoodItemReport", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("FoodReports")
                        .HasForeignKey("CalendarDayDate");

                    b.HasOne("ibDiary_data.Models.Food.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.Meal", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("CreatedMeals")
                        .HasForeignKey("CalendarDayDate");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.MealReport", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("MealReports")
                        .HasForeignKey("CalendarDayDate");

                    b.HasOne("ibDiary_data.Models.Food.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.Medicine", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("CreatedMedicines")
                        .HasForeignKey("CalendarDayDate");

                    b.HasOne("ibDiary_data.Models.Medication.MedicineSchedule", "MedicineSchedule")
                        .WithOne("Medicine")
                        .HasForeignKey("ibDiary_data.Models.Medication.Medicine", "MedicineScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicineSchedule");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.MedicineReport", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("MedicineReports")
                        .HasForeignKey("CalendarDayDate");

                    b.HasOne("ibDiary_data.Models.Medication.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.MedicineStateChange", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("MedicineStateChanges")
                        .HasForeignKey("CalendarDayDate");

                    b.HasOne("ibDiary_data.Models.Medication.Medicine", "Medicine")
                        .WithMany("StateChanges")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ibDiary_data.Models.Settings.ScheduledNotification", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("CreatedNotifications")
                        .HasForeignKey("CalendarDayDate");
                });

            modelBuilder.Entity("ibDiary_data.Models.Symptoms.Symptom", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("CreatedSymptoms")
                        .HasForeignKey("CalendarDayDate");
                });

            modelBuilder.Entity("ibDiary_data.Models.Symptoms.SymptomReport", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("SymptomReports")
                        .HasForeignKey("CalendarDayDate");

                    b.HasOne("ibDiary_data.Models.Medication.Medicine", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId");

                    b.HasOne("ibDiary_data.Models.Symptoms.Symptom", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("ibDiary_data.Models.Symptoms.SymptomStateChange", b =>
                {
                    b.HasOne("ibDiary_data.Models.Calendar.CalendarDay", null)
                        .WithMany("SymptomStateChanges")
                        .HasForeignKey("CalendarDayDate");

                    b.HasOne("ibDiary_data.Models.Symptoms.Symptom", "Symptom")
                        .WithMany("StateChanges")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("ibDiary_data.Models.Calendar.CalendarDay", b =>
                {
                    b.Navigation("CreatedFoods");

                    b.Navigation("CreatedMeals");

                    b.Navigation("CreatedMedicines");

                    b.Navigation("CreatedNotifications");

                    b.Navigation("CreatedSymptoms");

                    b.Navigation("FoodReports");

                    b.Navigation("MealReports");

                    b.Navigation("MedicineReports");

                    b.Navigation("MedicineStateChanges");

                    b.Navigation("SymptomReports");

                    b.Navigation("SymptomStateChanges");
                });

            modelBuilder.Entity("ibDiary_data.Models.Food.Meal", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.Medicine", b =>
                {
                    b.Navigation("StateChanges");
                });

            modelBuilder.Entity("ibDiary_data.Models.Medication.MedicineSchedule", b =>
                {
                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ibDiary_data.Models.Symptoms.Symptom", b =>
                {
                    b.Navigation("StateChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
